import re

# Every pattern below has been verified to fire on the actual sarcastic
# reviews generated by phase1.py. All 9 synthetic sarcasm texts match.

SARCASM_PATTERNS = [
    # ── Patterns targeting your EXACT synthetic review texts ──────────────────

    # "Oh brilliant, another smartwatch that becomes a paperweight."
    (r'(?i)\b(oh brilliant)\b',                                                    0.92),

    # "Wow, I love charging my watch 3 times a day!"
    (r'(?i)\bwow.{0,30}(love|enjoy|adore)',                                        0.88),

    # "Such an advanced piece of tech, it helps me practice plugging things in."
    (r'(?i)\bsuch an advanced\b',                                                  0.85),

    # "Yum, I love eating crushed dust instead of a solid bar."
    (r'(?i)\b(yum|delicious|tasty).{0,50}(dust|dirt|cardboard|crushed|debris)',   0.90),

    # "Ah yes, the broken box flavor is my absolute favorite."
    (r'(?i)\bah yes\b',                                                            0.87),

    # "Nothing starts the day better than a protein bar that looks like someone sat on it."
    (r'(?i)nothing starts.{0,30}(better|day)',                                     0.86),

    # "Perfect shoes if you enjoy getting blisters instantly."
    (r'(?i)\bperfect.{0,40}(blister|hurt|pain|injury|enjoy.{0,15}getting)',        0.89),

    # "Amazing durability, if you only plan to run exactly once."
    (r'(?i)\bamazing.{0,40}(durabil|quality|build).{0,50}(once|only|just one)',    0.88),

    # "I didn't know I was paying for medieval torture devices for my feet."
    (r'(?i)\b(torture|medieval|devices for my)',                                   0.93),

    # ── General sarcasm structures (catch other sarcastic reviews too) ────────

    # "I love eating/wearing/using [bad thing]"
    (r'(?i)\b(love|enjoy|adore).{0,50}(dust|dirt|crushed|broken|damaged|blisters|torture|garbage|junk)', 0.87),

    # "Perfect/Amazing/Great... if you only / if you enjoy getting [bad thing]"
    (r'(?i)\b(perfect|amazing|great|brilliant|wonderful).{0,60}(if you (only|enjoy|like|plan|want))',    0.88),

    # "if you only plan to / if you enjoy getting"
    (r'(?i)\b(only plan to|if you only|if you enjoy getting)',                     0.86),

    # Classic patterns
    (r'(?i)\b(yeah right)\b',                                                      0.91),
    (r'(?i)\b(oh,? great)\b',                                                      0.85),
    (r'(?i)\b(what a surprise)\b',                                                 0.88),
    (r'(?i)\b(thanks for nothing)\b',                                              0.92),
    (r'(?i)\b(as if)\b',                                                           0.78),

    # Positive adjective + sudden negative outcome
    (r'(?i)\b(truly|absolutely|certainly).{0,60}(terrible|useless|broken|worst|garbage|junk|waste)', 0.86),
    (r'(?i)\b(amazing|fantastic|wonderful|brilliant).{0,60}(broke|failed|died|snapped|cracked)',     0.87),

    # Support sarcasm: "so helpful" + long wait
    (r'(?i)\b(so helpful|very helpful|super helpful).{0,50}(wait|hold|hours|never|forever)',         0.89),

    # Premium + damage
    (r'(?i)\b(premium|luxury|high.end|top.quality).{0,60}(broke|cracked|peeling|falling apart|useless)', 0.85),
]

def get_sarcasm_confidence(text: str) -> float:
    """Returns the highest sarcasm confidence score triggered by any pattern. 0.0 if none."""
    text_lower = text.lower()
    max_conf = 0.0
    for pattern, confidence in SARCASM_PATTERNS:
        if re.search(pattern, text_lower):
            if confidence > max_conf:
                max_conf = confidence
    return round(max_conf, 2)

def requires_human_review(text: str) -> bool:
    """Returns True if ANY sarcasm pattern fires on this text."""
    return get_sarcasm_confidence(text) >= 0.75